import Head from 'next/head'
import { ArrowRightIcon, ChevronDownIcon, ChevronUpIcon, SettingsIcon } from '@chakra-ui/icons'
import { Box, Button, Container, FormControl, FormLabel, Heading, IconButton, Input, InputGroup, InputLeftAddon, InputRightAddon, Modal, ModalBody, ModalContent, ModalFooter, ModalHeader, ModalOverlay, Text, VStack, Wrap, WrapItem, useBoolean, useDisclosure } from '@chakra-ui/react'

export default function Home() {
  const { isOpen, onOpen, onClose } = useDisclosure()
  const [ advance, setAdvance ] = useBoolean()

  return (
    <>
      <Head>
        <title>Link Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Container pt={10} maxW={'container.md'}>
        <VStack spacing={10}>
          <Box>
            <Heading>
              Link Service
              <IconButton variant={'ghost'} icon={<SettingsIcon />} fontSize={'xl'} onClick={onOpen} />
            </Heading>
            <Modal isOpen={isOpen} onClose={onClose}>
              <ModalOverlay />
              <ModalContent>
                <ModalHeader>Set Key</ModalHeader>
                <ModalBody>
                  <Input placeholder='X-Custom-PSK' id='psk' />
                </ModalBody>

                <ModalFooter>
                  <Button colorScheme='teal' onClick={() => {
                    const psk = document.querySelector('#psk').value.trim()
                    localStorage.setItem('psk', psk)
                    onClose()
                  }}>
                    Save
                  </Button>
                </ModalFooter>
              </ModalContent>
            </Modal>
          </Box>
          <VStack w={'100%'} spacing={2}>
            <InputGroup>
              <InputLeftAddon children='URL' />
              <Input type='url' placeholder='https://the.url.com/that/you/want/to/shorten' autoComplete='off' />
              <InputRightAddon children={<ArrowRightIcon />} />
            </InputGroup>
            <Button variant={'ghost'} onClick={setAdvance.toggle}>
              Advance
              <ChevronDownIcon fontSize={'xl'} display={advance ? 'block' : 'none'} />
              <ChevronUpIcon fontSize={'xl'} display={advance ? 'none' : 'block'} />
            </Button>
            <Wrap display={advance ? 'block' : 'none'}>
              <WrapItem>
                <Text>Whatever</Text>
                <Input type='email' />
              </WrapItem>
            </Wrap>
          </VStack>
        </VStack>
      </Container>
    </>
  )
}
