import Head from 'next/head'
import { ArrowRightIcon, ChevronDownIcon, ChevronUpIcon, SettingsIcon } from '@chakra-ui/icons'
import { Box, Button, Container, Flex, FormControl, FormHelperText, FormLabel, Heading, IconButton, Input, InputGroup, InputLeftAddon, InputRightAddon, Modal, ModalBody, ModalContent, ModalFooter, ModalHeader, ModalOverlay, Select, SimpleGrid, Spacer, Stack, Switch, Text, VStack, Wrap, WrapItem, useBoolean, useDisclosure } from '@chakra-ui/react'

export default function Home() {
  const { isOpen, onOpen, onClose } = useDisclosure()
  const [ advance, setAdvance ] = useBoolean(true)

  return (
    <>
      <Head>
        <title>Link Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Container pt={10} maxW={'container.md'}>
        <Stack spacing={5}>
          <Flex>
            <Heading>Link Service</Heading>
            <Spacer />
            <IconButton variant={'ghost'} icon={<SettingsIcon />} fontSize={'xl'} onClick={onOpen} />
            <Modal isOpen={isOpen} onClose={onClose}>
              <ModalOverlay />
              <ModalContent>
                <ModalHeader>Set Key</ModalHeader>
                <ModalBody>
                  <Input placeholder='X-Custom-PSK' id='psk' />
                </ModalBody>

                <ModalFooter>
                  <Button colorScheme='teal' onClick={() => {
                    const psk = document.querySelector('#psk').value.trim()
                    localStorage.setItem('psk', psk)
                    onClose()
                  }}>
                    Save
                  </Button>
                </ModalFooter>
              </ModalContent>
            </Modal>
          </Flex>
          <VStack spacing={1}>
            <InputGroup>
              <InputLeftAddon children='URL' />
              <Input type='url' placeholder='https://the.url.com/that/you/want/to/shorten' autoComplete='off' />
              <InputRightAddon children={<ArrowRightIcon />} />
            </InputGroup>
            <Button variant={'ghost'} onClick={setAdvance.toggle}>
              Advance
              <ChevronDownIcon fontSize={'xl'} display={advance ? 'block' : 'none'} />
              <ChevronUpIcon fontSize={'xl'} display={advance ? 'none' : 'block'} />
            </Button>
            <Box display={advance ? 'block' : 'none'}>
              <SimpleGrid columns={[1, 2, 4]} spacingX={10} spacingY={2}>
                <FormControl>
                  <FormLabel>Alias</FormLabel>
                  <Input type='text' placeholder='random' autoComplete='off' />
                </FormControl>
                <FormControl>
                  <FormLabel>Duration</FormLabel>
                  <Select>
                    <option>1 hour</option>
                    <option selected>24 hours</option>
                    <option>3 days</option>
                    <option>7 days</option>
                    <option>30 days</option>
                    <option>Presistent</option>
                  </Select>
                </FormControl>
                <FormControl>
                  <FormLabel>Private?</FormLabel>
                  <Switch size='lg' />
                </FormControl>
                <FormControl>
                  <FormLabel>Burn after Read?</FormLabel>
                  <Switch size='lg' />
                </FormControl>
              </SimpleGrid>
            </Box>
          </VStack>
        </Stack>
      </Container>
    </>
  )
}
